namespace TradeStops.Common.Enums
{
    public enum HDEventTypes
    {
        CsiSplit                     = 1,
        CsiDividend                  = 2,
        CsiAddSymbol                 = 3,
        CsiDelistedSymbol            = 4,
        CsiModifySymbol              = 5,
        CsiPriceCorrection           = 6,
        CsiSplitCorrection           = 8,
        CsiDividendCorrection        = 9,
        CsiEarlySplitCorrection      = 10,
        CsiEarlyDividendCorrection   = 11,
        AddSymbol                    = 12,
        DelistedSymbol               = 13,
        CsiEarlyPriceCorrection      = 14,
        PinnaclePriceCorrection      = 15,
        DtnPriceCorrection           = 16,
        CsiVolumeCorrection          = 17,
        CsiEarlyVolumeCorrection     = 18,
        GenesisAddSymbol             = 19,
        GenesisRemoveSymbol          = 20,
        CsiHistoryDividendCorrection = 21,
        CsiHistorySplitCorrection    = 22,
        CsiUndelistedSymbol          = 23,
        StockDistribution            = 26,
        SpinOff                      = 27,
        StockDistributionCorrection  = 28,
        SpinOffCorrection            = 29,
        Manualcorrection             = 30,
        VolumeCorrection             = 31,
        VwapCorrection               = 32,
    }
}
