namespace TradeStops.Common.Enums
{
    public enum TriggerTypes
    {
        PercentOfAverageVolume     = 2,
        MovingAveragePrice         = 4,
        MovingAverageCrosses       = 5,
        CalendarDays               = 6,
        TradingDays                = 7,
        SpecificDate               = 9,
        ProfitableCloses           = 8,
        TrailingStopPercent        = 10,
        PercentageGainLoss         = 12,
        DollarGainLoss             = 13,
        FixedPrice                 = 14,
        NakedPut                   = 34,
        CoveredCall                = 35,
        UnStockFixedPrice          = 39,
        PercentageTimeValue        = 40,
        DollarTimeValue            = 41,
        Expiry                     = 42,
        Breakout                   = 43,
        UnStockTrailingStopPercent = 44,
        Target                     = 45,
        VolatilityQuotinent        = 46,
        UnStockVolatilityQuotinent = 47,
        StockStateIndicator        = 52,
        TwoVolatilityQuotient      = 53,
        TrailingStopMinusDividend  = 54,
        EntrySignal                = 55,
        EarlyEntrySignal           = 56,
        NewHighProfit              = 57,
        StockRating                = 58,
    }
}
